sudo: required

language: php
php:
- '7.1.9'

# services:
#   - docker

branches:
  only:
  - master

# travis runtime environment from here or settings. : https://docs.travis-ci.com/user/environment-variables/
env:
  global:
    - ZIP_FILE="php-web-$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT.zip"

    # travis-ci secure doc : https://docs.travis-ci.com/user/encryption-keys/
    # before install travis , first install ruby & gem
    # $ gem install travis
    # $ travis encrypt SOMEVAR="secretvalue"

    # AWS_ACCESS_KEY_ID_DEV
    - secure: ""
    # AWS_SECRET_ACCESS_KEY_DEV
    - secure: ""
    # AWS_ACCESS_KEY_ID_STG
    #    - secure: ""
    # AWS_SECRET_ACCESS_KEY_STG
    #    - secure: ""
    # AWS_ACCESS_KEY_ID_PROD , value : AKI....QMQ
    - secure: "sko3bIx/LBI3g2vu3Nk96voeQ8vvfXshxGbhrkBenjl4+3rOvnEgruh9cv5wab9D1JGDuPO+zHzHGciGJLTbCdYWyPy0ADVQLAZAwnHK3x7Rds2fjm9O17OR/u08bSsg763KonsIY7HcHlwooCN+FWoEHjBZOjFzz5sCrRAYsVdjaPcWVrQAzgzq3CKneIMMhZbmhLquzEg7FOOce/PGrooHP16e8k4nJu8gc1Urr5JzXYg/gyIXjHqTRfJfwjA22XaPLh5xRWA52YeEb3FxHzOIsgehsWuzDMtNffIwJygagkKNYJ01MGWPbbu96kTO2BxjcsTL0VvhLqyRVt70CltVYfsEwvJqKc7qmvzoF6+U+kluA2VPtLb0xvGYLBa1CzT7i/EJVRMOH/CylvGszrn+CIFRez7SY1cZJGYrebVvEP35VpkXUT1bdCxASyYX+UCFuJupq7Hr4VJkR+O7NOUuBeP1Zo8+VoghroKiPmfAPqPkHp6RMWHlGDm+WWPXsnObyIQt7RjDEbU5uZ+Q0spDNi1Rj236otEVCVhbwrJ3Wf1euiFvNoCem/6WSctDAfudt7CdNLcBa0zuSulLvTL8qfuOwNpk1KgMRhHzYe/bNzhGRAjBE7xpt949mufTMCe41+PkoLng8lnOfYJjAd+Nx6iutgPViL2hDQwDSuM="
    # AWS_SECRET_ACCESS_KEY_PROD
    - secure: "KfMcKGKz8Y+slhinoZKmCgTanGPEBUwOltWkfoKzj9PgaILnwQSx8Gv+3cujPTrCqkeu7/WaRAaN2WzomHX+QDnGQCD8w++mGHUfxgDPFwzlSXSuJelG9KN+J3lfZO6X2S+CHoqDJKD8OZpQrsHD1pzHESAD4DEbStN+eFtVv4ICHqlEPLCoXyqyBswoSAC2Fx1+L2RIj8iEmSwfzV6orFFTWKvtaY5S9eVvBZ+7q/owEWzf4QyRFu42M/IXjq1RbicekEFaODuRYwcdFJZupoPgi0zVAEh1vsqwPdG2MV3HUe3ew5e8PxwRkntli5LKmDGTTJNuDR4AKbmcg9OeTxjMI9ZtQKTJjVygyiMcy2xac+nnWMb8odw7OLmqKZHmYh1btjPEgpY2fhZkxzEUpbbfSObCtMQFh1PutPxMfrSJcuU18QdmHeZLbmv3ejUFmAF04ZAI9e8AaE/x/ze/0uxhzXI3YfCdMmdIYnX55kx4kN14D3mVXuQ9/bT7CzLH/486gjcTUWdUYU2pkt5zZrAvYPpDuwjq+5cJgck5JZYm4Czk1w5p72RetK+zm8yXBa8901siPhkoWQkPbTifyk5Poqazq7kUNZcgZ/b/YlSPlSp3RuHOeg+ez4w+heMmCZJrCTGzj4+ZgxkKt876bKHUkUzN7gp+LnsVPvOBtXM="

    # global variables
    - AWS_ACCESS_KEY_ID=''
    - AWS_SECRET_ACCESS_KEY=''
    - AWS_REGION='ap-northeast-1'
    - S3_BUCKET=''
    - S3_FOLDER='demo1123'
    - CODEDEPLOY_APP_NAME=''
    - CODEDEPLOY_GROUP=''


# notification - https://docs.travis-ci.com/user/notifications
# notifications:
#   email:
#     recipients:
#       - one@example.com
#       - other@example.com
#     on_success: never # default: change
#     on_failure: always # default: always
# integration to slack , setup on slack travis-ci app
notifications:
  email:
    on_failure: always
    on_success: never
  #slack:
    #secure: "nUYjAZGN+uymXquFddUgPkbD/06atgwjWBRINpn3Hgq54+iJ8mSKJ5jSUaKUV4TCaQkwwv8+8GhwGTYeTkPq6/UBGQWeIVgfhzN0iXfjjhaBu0VhWzzeLfDFbD6ok0XRYdXYVnu3G3il7iXNSbCMH8jwsnrNvZNNEDovNxMA1LmPJ5v6Gg/+kGrngxYW0lIl/0+81TEBaVKo1KeIaEirRzIlN15tTNC6t3o9zV1dXaAE2H6ZbJLYj+NpsPCPYgjUf1seMBRCrMbTKcUu9yf2jwxXqZigtdmTAW5EZGro1ESv/v2kCnMmL5bmuDRizRw7CCnAANJQdJ3jVzVGK289+S/AqdcjGMYQxFRq/iyi4T6BZIbrHOTnKWwGq18djrEFxEysL6AC1rEDg7MTw2uQpiUAFIJff3PnXLEjJbKB/DR9zn3oLij4bxJ4CdnYwxZZvQO1zhQj2GhTzOYZ/G+DW3auuQI2ufVYaAiJf9NLoYLa1XXOyChAJhV3LEnZO8x78IRxwAmQKm/K6sTBIzXZXdb/heKCibnAEYUv7ZsKf8JzIKcv0nLreARqjBoUH181O+zhcjIdJKXmloQ67lUbtOFZD6jPQ1K/W1JZoAWcjX24g1VaApYPbMJDs8hMfZNFO/s52J/UQ3zy9WWUQK6Vp1AZgqErXEqO2+3MLh/wOhI="

cache:
  directories:
  - $COMPOSER_CACHE_DIR
  - $HOME/.composer/cache




# build lifecycle - https://docs.travis-ci.com/user/customizing-the-build/
# (OPTIONAL) Install apt addons
# (OPTIONAL) Install cache components
# before_install
# install
# before_script
# script
# (OPTIONAL) before_cache (for cleaning up cache)
# after_success or after_failure
# (OPTIONAL) before_deploy
# (OPTIONAL) deploy
# (OPTIONAL) after_deploy
# after_script

# set -e : when error stop build.
before_install:
  - set -e
  - echo `date +"%Y-%m-%d %H:%M:%S"`
  - echo $TRAVIS_BRANCH
  - if [[ $TRAVIS_BRANCH == "dev" ]]; then
      AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV;
      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV;
      S3_BUCKET='';
      CODEDEPLOY_APP='';
      CODEDEPLOY_GROUP='';
    fi
  - if [[ $TRAVIS_BRANCH == "staging" ]]; then
      AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STG;
      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STG;
      S3_BUCKET='';
      CODEDEPLOY_APP='';
      CODEDEPLOY_GROUP='';
    fi
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
      AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD;
      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD;
      S3_BUCKET='demo';
      CODEDEPLOY_APP='demo';
      CODEDEPLOY_GROUP='ec2';
    fi


# put testing scripts here 
script:
- echo 'script step...'

before_deploy:
- cd "$TRAVIS_BUILD_DIR";
  mkdir "$TRAVIS_BUILD_DIR/zip";
  zip -r "$TRAVIS_BUILD_DIR/zip/$ZIP_FILE" *


deploy:
- provider: S3
  access_key_id: &aws_access_key $AWS_ACCESS_KEY_ID
  secret_access_key: &aws_secret_key
    secure: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  local_dir: $TRAVIS_BUILD_DIR/zip
  bucket: $S3_BUCKET
  upload-dir: $S3_FOLDER
  skip_cleanup: true
  on:
    all_branches: true

- provider: codedeploy
  access_key_id: *aws_access_key
  secret_access_key: *aws_secret_key
  region: $AWS_REGION
  bucket: $S3_BUCKET
  key: $S3_FOLDER/$ZIP_FILE
  bundle_type: zip
  application: $CODEDEPLOY_APP
  deployment_group: $CODEDEPLOY_GROUP
  wait-until-deployed: true
  on:
    all_branches: true
